Allow -e multiple time
COVESA/vss-tools pull request #381
Opened 2024-07-19 13:15 UTC by erikbosch

I sometimes think our current approach of specifying multiple extended arguments as a comma separated list (without blanks) as not that intuitive. This PR adds the possibility to use the argument multiple times instead. It also adds some testcases that are good to keep even if you think the change sucks.

**Current solution**

```
-e a,b

# or

--extended-arguments a,b
```

**Proposal**
This PR adds the possibility to also use
```
-e a -e b

# or

--extended-arguments a --extended-arguments b
```

Discussion topics:

- Do we think this would be an improvement?
- If so, do we want to promote both styles (or better deprecating the old one for later removal in 6.0 or so)

2024-07-19 13:24 UTC, sschleemilch commented
#378 introduces that already: https://github.com/COVESA/vss-tools/pull/378/files#diff-b6edd36e3b26ecd6c94d19d1a0484fce6cbb7f88d11330368b6b55666afb5daeR37

2024-07-19 13:26 UTC, sschleemilch requested changes
Duplicate #378

2024-07-19 13:30 UTC, erikbosch commented
> Duplicate #378

Greats minds thinks alike. I will review that one now!

2024-07-19 13:33 UTC, sschleemilch commented
> > Duplicate #378
> 
> Greats minds thinks alike. I will review that one now!

Just merged master, we had merge conflits with #379.

2024-07-19 14:25 UTC, erikbosch commented
Putting this one on hold for now. I can confirm that repeated `-e` works in the other PR. The test cases from this PR and some of the documentation updates might be relevant to keep, I will visit it again after the other is merged.

2024-07-22 11:50 UTC, erikbosch commented
@sschleemilch - reworked this one now. I think it could be useful to give an error if someone use the old syntax with comma

2024-07-23 08:09 UTC, sschleemilch requested changes

2024-07-23 08:09 UTC, sschleemilch commented on docs/vspec.md
> +*Note: A comma separated list can no longer be used to specify extended attributes!*
maybe use an [alert](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts)

2024-07-23 08:09 UTC, sschleemilch commented on src/vss_tools/vspec/vssexporters/utils.py
> +        for item in VSSNode.whitelisted_extended_attributes:
The better place would be to do that directly in the [cli_options.py](https://github.com/COVESA/vss-tools/blob/master/src/vss_tools/vspec/cli_options.py) where the argument is defined.

We can write a function and define it for the `type=`:

```python
from click import option

def no_comma_type(value):
    if "," in value:
        raise click.BadParameter(f"'{value}' should not contain ','")

extend_all_attributes_opt = option(
    "--extend-all-attributes/--no-extend-all-attributes",
    help="""
        Generates all extended attributes,
        not only the ones given via '-e/--extended-attributes'
    """,
    default=False,
    show_default=True,
    type=no_comma_type
)
```

2024-07-23 09:02 UTC, sschleemilch approved these changes

2024-07-24 08:38 UTC, merged